### ISSUE TITLE
Examples of promises

### ISSUE THREAD

**Issue by marklawlor** [KoryNunn/righto-v-promise#1]
Hey Kory, sorry I missed your presentation. 

At BrisJS social drinks you wanted to talk about promises and their implementations, heres a couple of examples on how I'd write your example.
## Using async/await

My preferred method

```
// Available now with Babel/Typescript/Transpiling and coming very soon on all major platforms
// Node: https://github.com/nodejs/promises/issues/4
// Chrome: https://bugs.chromium.org/p/v8/issues/detail?id=4483
// Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1185106

async function doAsyncThing(){
    var user = await db.Users.get({id: 1});
    var profile = await db.Profile.get(user.get(user => ({id: user.profileId})));

    function combine(user, profile){
        return {...user, profile};
    }

    return combine(user, profile);
}
```
## Using a Promise control flow library

https://www.npmjs.com/package/co

```
// Works on anything that supports generators. Generators can be transpiled to ES5 to support older browsers

function doAsyncThing(){
    return co(function * () {
        var user = yield db.Users.get({id: 1});
        var profile = yield db.Profile.get(user.get(user => ({id: user.profileId})));

        function combine(user, profile){
            return {...user, profile};
        }

        return combine(user, profile);
    })
}
```
## Native Implementation

```
function doAsyncThing(){

  function combine(user, profile){
    return {...user, profile};
  }

  return db.Users.get({id: 1}).then(user => {
    return db.Profile.get(user.get(userInstance => ({id: userInstance.profileId}))).then(profile => {
      return combine(user, profile)
    })
  })
}
```

**Comment by KoryNunn** [comment]
Thanks for the examples.

I'm keeping this specifically vanilla promises (or at least as vanilla as you can get these days, which usually means bluebird)

Adding a control flow lib kinda defeats the purpose, since that's what promises were supposed to do in the first place, and what methods like `join` somewhat help with.

My first 'native' version looked like the one you have there, but it was deemed unfair to not use `join`, since it is a defacto standard method, and without it, the solution gets messy, giving you "then-hell".

As a note: your 'preferred' method looks almost identical to the righto solution.

**Comment by KoryNunn** [comment]
Also, your examples use `user.get(user => ({id: user.profileId}))` which is a method provided by righto, not the db object, which is just a plain old object, so they would need a bit more code to make them work.

**Comment by KoryNunn** [comment]
This is how the first one should be written (with my limited understanding of async/await)

```
async function doAsyncThing(){
    var user = await db.Users.get({id: 1});
    var profile = await db.Profile.get({id: user.profileId});

    return {...user, profile};
}
```

which is much shorter.

**Comment by KoryNunn** [comment]
Your async/await version actually gave me an idea of a feature to add to righto, which I've updated the README to reflect.
